language: node.js

node_js:
  - 7

services:
  - mongodb

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
  - npm install
env:
  - MONGODB_URL="mongodb://travis:test@mydb_test.ghuyv.mongodb.net/mydb_test?retryWrites=true&w=majority"
  - PORT=8090